/*
 * Master List of CUPS and SOAT Codes for Med-iTrack
 * This file is used for fuzzy matching and mapping of medical procedures.
 */

import { GENERATED_CUPS_METADATA } from './generated/cups.generated';
import type { CupsModality } from './generated/cups.generated';

const LEGACY_CODES: Record<string, string> = {
  // --- RADIOGRAFÍA (RX) ---
  '870001': 'RADIOGRAFIA DE CRANEO SIMPLE',
  '870002': 'PERFILOGRAMA CON CEFALOMETRIA',
  '870003': 'RADIOGRAFIA DE BASE DE CRANEO',
  '870004': 'RADIOGRAFIA DE SILLA TURCA',
  '870005': 'RADIOGRAFIA DE MASTOIDES COMPARATIVAS',
  '870006': 'RADIOGRAFIA DE PEÑASCOS',
  '870007': 'RADIOGRAFIA DE CONDUCTO AUDITIVO INTERNO',
  '870101': 'RADIOGRAFIA DE CARA (PERFILOGRAMA)',
  '870102': 'RADIOGRAFIA DE ORBITAS',
  '870103': 'RADIOGRAFIA DE AGUJEROS OPTICOS',
  '870104': 'RADIOGRAFIA DE MALAR',
  '870105': 'RADIOGRAFIA DE ARCO CIGOMATICO',
  '870107': 'RADIOGRAFIA DE HUESOS NASALES',
  '870108': 'RADIOGRAFIA DE SENOS PARANASALES',
  '870112': 'RADIOGRAFIA DE MAXILAR SUPERIOR',
  '870131': 'RADIOGRAFIA DE ARTICULACION TEMPOROMAXILAR [ATM]',
  '870601': 'RADIOGRAFIA DE TEJIDOS BLANDOS DE CUELLO',
  '870602': 'RADIOGRAFIA DE CAVUM FARINGEO',
  '870603': 'RADIOGRAFIA DE FARINGE [FARINGOGRAFIA]',
  '871010': 'RADIOGRAFIA DE COLUMNA CERVICAL',
  '871019': 'RADIOGRAFIA DE COLUMNA UNION CERVICO DORSAL',
  '871020': 'RADIOGRAFIA DE COLUMNA TORACICA',
  '871030': 'RADIOGRAFIA DE COLUMNA DORSOLUMBAR',
  '871040': 'RADIOGRAFIA DE COLUMNA LUMBOSACRA',
  '871050': 'RADIOGRAFIA DE SACRO COCCIX',
  '871060': 'RADIOGRAFIA DE COLUMNA VERTEBRAL TOTAL',
  '871070': 'RADIOGRAFIA DINAMICA DE COLUMNA VERTEBRAL',
  '871091': 'RADIOGRAFIA DE ARTICULACIONES SACROILIACAS',
  '871111': 'RADIOGRAFIA DE REJA COSTAL',
  '871112': 'RADIOGRAFIA DE ESTERNON',
  '871121': 'RADIOGRAFIA DE TORAX (P.A. O A.P. Y LATERAL)',
  '871129': 'RADIOGRAFIA DE ARTICULACIONES ESTERNOCLAVICULARES',
  '871320': 'RADIOGRAFIA DE ESOFAGO',
  '872002': 'RADIOGRAFIA DE ABDOMEN SIMPLE',
  '872011': 'RADIOGRAFIA DE ABDOMEN SIMPLE (ABDOMEN AGUDO)',
  '872101': 'RADIOGRAFIA DE TRANSITO INTESTINAL CONVENCIONAL',
  '872102': 'RADIOGRAFIA DE TRANSITO INTESTINAL DOBLE CONTRASTE',
  '872103': 'RADIOGRAFIA DE TRANSITO INTESTINAL CON MARCADORES',
  '872104': 'RADIOGRAFIA DE COLON POR ENEMA',
  '872105': 'RADIOGRAFIA DE COLON POR ENEMA CON DOBLE CONTRASTE',
  '872121': 'RADIOGRAFIA DE VIAS DIGESTIVAS ALTAS',
  '872122': 'RADIOGRAFIA DE VIAS DIGESTIVAS ALTAS CON DOBLE CONTRASTE',
  '872123': 'RADIOGRAFIA DE VIAS DIGESTIVAS ALTAS Y TRANSITO INTESTINAL',
  '873001': 'RADIOGRAFIA PARA SERIE ESQUELETICA',
  '873002': 'RADIOGRAFIA DE HUESOS LARGOS SERIE COMPLETA',
  '873003': 'RADIOGRAFIA PARA ESTUDIOS DE LONGITUD DE LOS HUESOS',
  '873004': 'RADIOGRAFIA PARA DETECTAR EDAD OSEA [CARPOGRAMA]',
  '873111': 'RADIOGRAFIA DE OMOPLATO',
  '873112': 'RADIOGRAFIA DE CLAVICULA',
  '873121': 'RADIOGRAFIA DE HUMERO',
  '873122': 'RADIOGRAFIA DE ANTEBRAZO',
  '873123': 'RADIOGRAFIAS COMPARATIVAS DE EXTREMIDADES SUPERIORES',
  '873202': 'RADIOGRAFIA DE ARTICULACIONES ACROMIO CLAVICULARES',
  '873204': 'RADIOGRAFIA DE HOMBRO',
  '873205': 'RADIOGRAFIA DE CODO',
  '873206': 'RADIOGRAFIA DE PUÑO O MUÑECA',
  '873210': 'RADIOGRAFIA DE MANO',
  '873302': 'RADIOGRAFIA PARA MEDICION DE MIEMBROS INFERIORES [FARILL]',
  '873303': 'RADIOGRAFIA COMPARATIVA DE PIES CON APOYO',
  '873304': 'RADIOGRAFIA AXIAL DE SESAMOIDEOS',
  '873311': 'RADIOGRAFIA DE ANTEVERSION FEMORAL',
  '873312': 'RADIOGRAFIA DE FEMUR (AP - LATERAL)',
  '873313': 'RADIOGRAFIA DE PIERNA (AP - LATERAL)',
  '873314': 'RADIOGRAFIA DE ANTEVERSION TIBIAL',
  '873333': 'RADIOGRAFIA DE PIE (AP - LATERAL Y OBLICUA)',
  '873335': 'RADIOGRAFIA DE CALCANEO (AXIAL Y LATERAL)',
  '873340': 'RADIOGRAFIA DE MIEMBRO INFERIOR (AP - LATERAL)',
  '873411': 'RADIOGRAFIA DE CADERA (AP - LATERAL)',
  '873412': 'RADIOGRAFIA DE CADERA COMPARATIVA',
  '873420': 'RADIOGRAFIA DE RODILLA (AP - LATERAL)',
  '873422': 'RADIOGRAFIA DE RODILLAS COMPARATIVAS VERTICAL',
  '873423': 'RADIOGRAFIA TANGENCIAL O AXIAL DE ROTULA',
  '873431': 'RADIOGRAFIA DE TOBILLO (AP - LATERAL)',
  '873443': 'RADIOGRAFIAS COMPARATIVAS DE EXTREMIDADES INFERIORES',
  '873444': 'RADIOGRAFIAS EN EXTREMIDADES PROYECCIONES ADICIONALES',
  '873501': 'FLUOROSCOPIA COMO GUIA PARA PROCEDIMIENTOS',
  '876801': 'MAMOGRAFIA UNILATERAL',
  '876802': 'MAMOGRAFIA BILATERAL',
  '876901': 'GALACTOGRAFIA DE UN CONDUCTO',
  '876902': 'GALACTOGRAFIA DE MULTIPLES CONDUCTOS',
  '877602': 'COLANGIOGRAFIA POR TUBO O CATETER',
  '877603': 'COLANGIOGRAFIA PERCUTANEA',
  '877802': 'UROGRAFIA INTRAVENOSA',
  '877812': 'PIELOGRAFIA A TRAVES DE TUBO DE NEFROSTOMIA',
  '877814': 'PIELOGRAFIA RETROGRADA',
  '877815': 'PIELOGRAFIA RETROGRADA O ANTEROGRADA',
  '877816': 'PIELOGRAFIA PERCUTANEA',
  '877831': 'URETEROGRAFIA RETROGRADA',
  '877851': 'CISTOGRAFIA CON PROYECCIONES OBLICUAS',
  '877861': 'URETROCISTOGRAFIA',
  '877862': 'URETROCISTOGRAFIA MICCIONAL',
  '877863': 'URETROCISTOGRAFIA RETROGRADA',
  '877871': 'URETROGRAFIA RETROGRADA',

  // --- TOMOGRAFÍA (TAC) ---
  '879111': 'TOMOGRAFIA COMPUTADA DE CRANEO SIMPLE',
  '879112': 'TOMOGRAFIA COMPUTADA DE CRANEO CON CONTRASTE',
  '879113': 'TOMOGRAFIA COMPUTADA DE CRANEO SIMPLE Y CON CONTRASTE',
  '879116': 'TOMOGRAFIA COMPUTADA DE SILLA TURCA (HIPOFISIS)',
  '879121': 'TOMOGRAFIA COMPUTADA DE ORBITAS',
  '879122': 'TOMOGRAFIA COMPUTADA DE OIDO - PEÑASCO',
  '879131': 'TOMOGRAFIA COMPUTADA DE SENOS PARANASALES O CARA',
  '879132': 'TOMOGRAFIA COMPUTADA DE RINOFARINGE',
  '879141': 'TOMOGRAFIA COMPUTADA DE MAXILARES',
  '879150': 'TOMOGRAFIA COMPUTADA DE ATM (BILATERAL)',
  '879161': 'TOMOGRAFIA COMPUTADA DE CUELLO',
  '879162': 'TOMOGRAFIA COMPUTADA DE LARINGE',
  '879201': 'TOMOGRAFIA COMPUTADA DE COLUMNA (TRES ESPACIOS)',
  '879205': 'TOMOGRAFIA COMPUTADA DE COLUMNA (COMPLEMENTO MIELOGRAFIA)',
  '879301': 'TOMOGRAFIA COMPUTADA DE TORAX',
  '879302': 'TOMOGRAFIA COMPUTADA DE CORAZON Y GRANDES VASOS',
  '879303': 'TOMOGRAFIA COMPUTADA DE TORAX DE BAJA DOSIS',
  '879304': 'TOMOGRAFIA COMPUTADA DE TORAX DE ALTA RESOLUCION',
  '879391': 'TOMOGRAFIA COMPUTADA DE TORAX EXTENDIDO AL ABDOMEN',
  '879410': 'TOMOGRAFIA COMPUTADA DE ABDOMEN SUPERIOR',
  '879411': 'TOMOGRAFIA COMPUTADA de INTESTINO [ENTEROTC]',
  '879420': 'TOMOGRAFIA COMPUTADA DE ABDOMEN Y PELVIS (TOTAL)',
  '879421': 'TOMOGRAFIA COMPUTADA DE CADERA',
  '879430': 'TOMOGRAFIA COMPUTADA DE VIAS URINARIAS [UROTC]',
  '879431': 'UROGRAFIA CON TOMOGRAFIA COMPUTADA',
  '879460': 'TOMOGRAFIA COMPUTADA DE PELVIS',
  '879510': 'TOMOGRAFIA COMPUTADA DE MIEMBROS SUPERIORES',
  '879520': 'TOMOGRAFIA COMPUTADA DE MIEMBROS INFERIORES',
  '879522': 'TOMOGRAFIA COMPUTADA DE MIEMBROS INFERIORES (ANTEVERSION)',
  '879523': 'TOMOGRAFIA COMPUTADA DE MIEMBROS INFERIORES (AXIALES ROTULA)',
  '879901': 'TOMOGRAFIA COMPUTADA DE VASOS',
  '879902': 'TOMOGRAFIA COMPUTADA DE CORONARIAS [ANGIOTC]',
  '879903': 'TOMOGRAFIA COMPUTADA CON PERFUSION',
  '879904': 'TOMOGRAFIA DE COHERENCIA OPTICA ENDOVASCULAR',
  '879905': 'TOMOGRAFIA COMPUTADA OSEA DE CUERPO ENTERO',
  '879910': 'TOMOGRAFIA COMPUTADA RECONSTRUCCION TRIDIMENSIONAL',
  '879911': 'TOMOGRAFIA COMPUTADA RECONSTRUCCION VIRTUAL',
  '879920': 'TOMOGRAFIA COMPUTADA CON MODALIDAD DINAMICA',
  '879990': 'TOMOGRAFIA COMPUTADA COMO GUIA PARA PROCEDIMIENTOS',
  '872520': 'COLANGIOGRAFIA-TOMOGRAFIA',

  // --- ECOGRAFÍA (ECO) ---
  '881112': 'ECOGRAFIA CEREBRAL TRANSFONTANELAR',
  '881118': 'ECOGRAFIA CEREBRAL TRANSFONTANELAR CON DOPPLER',
  '881130': 'ECOGRAFIA DE TEJIDOS BLANDOS DE CARA',
  '881131': 'ECOGRAFIA DE GLANDULAS SALIVALES',
  '881132': 'ECOGRAFIA DE CUELLO',
  '881141': 'ECOGRAFIA DE TIROIDES',
  '881151': 'ECOGRAFIA DE GLANGLIOS CERVICALES (MAPEO)',
  '881201': 'ECOGRAFIA DE MAMA',
  '881211': 'ECOGRAFIA DE TORAX (PERICARDIO O PLEURA)',
  '881212': 'ECOGRAFIA DE OTROS SITIOS TORACICOS',
  '881213': 'ECOGRAFIA ENDOSCOPICA DE MEDIASTINO',
  '881215': 'ECOGRAFIA ENDOSCOPICA DE PULMON',
  '881301': 'ECOGRAFIA DE TEJIDOS BLANDOS DE PARED ABDOMINAL',
  '881302': 'ECOGRAFIA DE ABDOMEN TOTAL',
  '881305': 'ECOGRAFIA DE ABDOMEN SUPERIOR',
  '881306': 'ECOGRAFIA DE HIGADO - PANCREAS - VIA BILIAR',
  '881312': 'ECOGRAFIA ENDOSCOPICA DE ESOFAGO',
  '881313': 'ECOGRAFIA DE ABDOMEN (PILORO)',
  '881314': 'ECOGRAFIA ENDOSCOPICA DE ESTOMAGO O DUODENO',
  '881317': 'ECOGRAFIA ENDOSCOPICA BILIOPANCREATICA',
  '881318': 'ECOGRAFIA DE RECTO',
  '881319': 'ECOGRAFIA ENDOSCOPICA DE RECTO',
  '881320': 'ECOGRAFIA DE ANO',
  '881321': 'ECOGRAFIA LAPAROSCOPICA DE ABDOMEN',
  '881332': 'ECOGRAFIA DE VIAS URINARIAS',
  '881360': 'ECOGRAFIA PELVICA CON ANALISIS DOPPLER',
  '881361': 'ECOGRAFIA INTESTINAL CON ANALISIS DOPPLER',
  '881362': 'ECOGRAFIA DE TEJIDOS BLANDOS CON ANALISIS DOPPLER',
  '881390': 'ECOGRAFIA ABDOMEN Y PELVIS GUIA PROCEDIMIENTO',
  '881401': 'ECOGRAFIA PELVICA GINECOLOGICA TRANSVAGINAL',
  '881402': 'ECOGRAFIA PELVICA GINECOLOGICA TRANSABDOMINAL',
  '881403': 'ECOGRAFIA PELVICA INTEGRAL FOLICULAR',
  '881410': 'ECOGRAFIA PELVICA GINECOLOGICA HISTEROSONOGRAFIA',
  '881411': 'ECOGRAFIA DINAMICA DE PISO PELVICO',
  '881412': 'ECOGRAFIA DE MAPEO PELVICO',
  '881431': 'ECOGRAFIA OBSTETRICA TRANSABDOMINAL',
  '881432': 'ECOGRAFIA OBSTETRICA TRANSVAGINAL',
  '881434': 'PERFIL BIOFISICO',
  '881435': 'ECOGRAFIA OBSTETRICA CON EVALUACION CIRCULACION',
  '881436': 'ECOGRAFIA OBSTETRICA CON TRANSLUCENCIA NUCAL',
  '881437': 'ECOGRAFIA OBSTETRICA CON DETALLE ANATOMICO',
  '881501': 'ECOGRAFIA DE PROSTATA TRANSABDOMINAL',
  '881502': 'ECOGRAFIA DE PROSTATA TRANSRECTAL',
  '881510': 'ECOGRAFIA TESTICULAR',
  '881511': 'ECOGRAFIA TESTICULAR CON ANALISIS DOPPLER',
  '881521': 'ECOGRAFIA DE PENE',
  '881601': 'ECOGRAFIA DE TEJIDOS BLANDOS EXTREMIDADES SUPERIORES',
  '881602': 'ECOGRAFIA de TEJIDOS BLANDOS EXTREMIDADES INFERIORES',
  '881610': 'ECOGRAFIA ARTICULAR DE HOMBRO',
  '881611': 'ECOGRAFIA ARTICULAR DE CODO',
  '881612': 'ECOGRAFIA ARTICULAR DE PUÑO (MUÑECA)',
  '881613': 'ECOGRAFIA ARTICULAR DE MANO',
  '881620': 'ECOGRAFIA ARTICULAR DE RODILLA',
  '881621': 'ECOGRAFIA ARTICULAR DE TOBILLO',
  '881622': 'ECOGRAFIA ARTICULAR DE PIE',
  '881630': 'ECOGRAFIA ARTICULAR DE CADERA',
  '881640': 'ECOGRAFIA DE CALCANEO',
  '881701': 'ECOGRAFIA COMO GUIA PARA PROCEDIMIENTOS',
  '882103': 'ECOGRAFIA DOPPLER TRANSCRANEAL',
  '882112': 'ECOGRAFIA DOPPLER DE VASOS DEL CUELLO',
  '882203': 'ECOGRAFIA DOPPLER DE VASOS ABDOMINALES O PELVICOS',
  '882212': 'ECOGRAFIA DOPPLER DE AORTA ABDOMINAL',
  '882222': 'ECOGRAFIA DOPPLER DE ARTERIAS RENALES',
  '882307': 'ECOGRAFIA DOPPLER ARTERIAS MIEMBROS SUPERIORES',
  '882308': 'ECOGRAFIA DOPPLER ARTERIAS MIEMBROS INFEIORES',
  '882309': 'ECOGRAFIA DOPPLER VENAS MIEMBROS SUPERIORES',
  '882317': 'ECOGRAFIA DOPPLER VENAS MIEMBROS INFERIORES',

  // --- RESONANCIA (RMN) ---
  '883101': 'RESONANCIA MAGNETICA DE CEREBRO',
  '883102': 'RESONANCIA MAGNETICA DE BASE DE CRANEO O SILLA TURCA',
  '883103': 'RESONANCIA MAGNETICA DE ORBITAS',
  '883105': 'RESONANCIA MAGNETICA DE ATM',
  '883108': 'RESONANCIA MAGNETICA DE PARES CRANEANOS',
  '883109': 'RESONANCIA MAGNETICA DE OIDOS',
  '883110': 'RESONANCIA MAGNETICA DE SENOS PARANASALES O CARA',
  '883111': 'RESONANCIA MAGNETICA DE CUELLO',
  '883210': 'RESONANCIA MAGNETICA DE COLUMNA CERVICAL SIMPLE',
  '883211': 'RESONANCIA MAGNETICA DE COLUMNA CERVICAL CON CONTRASTE',
  '883220': 'RESONANCIA MAGNETICA DE COLUMNA TORACICA SIMPLE',
  '883221': 'RESONANCIA MAGNETICA DE COLUMNA TORACICA CON CONTRASTE',
  '883230': 'RESONANCIA MAGNETICA DE COLUMNA LUMBOSACRA SIMPLE',
  '883231': 'RESONANCIA MAGNETICA DE COLUMNA LUMBAR CON CONTRASTE',
  '883232': 'RESONANCIA MAGNETICA DE ARTICULACION SACROILIACA SIMPLE',
  '883234': 'RESONANCIA MAGNETICA DE COLUMNA SACROCOXIGEA SIMPLE',
  '883301': 'RESONANCIA MAGNETICA DEL TORAX',
  '883351': 'RESONANCIA MAGNETICA DE MAMA',
  '883401': 'RESONANCIA MAGNETICA DE ABDOMEN',
  '883430': 'RESONANCIA MAGNETICA DE VIAS BILIARES',
  '883434': 'COLANGIORESONANCIA',
  '883435': 'RESONANCIA MAGNETICA DE VIA URINARIA [URORRESONANCIA]',
  '883436': 'RESONANCIA MAGNETICA DE INTESTINO [ENTERORM]',
  '883440': 'RESONANCIA MAGNETICA DE PELVIS',
  '883511': 'RESONANCIA MAGNETICA DE MIEMBRO SUPERIOR',
  '883512': 'RESONANCIA MAGNETICA DE ARTICULACIONES MIEMBRO SUPERIOR',
  '883521': 'RESONANCIA MAGNETICA DE MIEMBRO INFERIOR',
  '883522': 'RESONANCIA MAGNETICA DE ARTICULACIONES MIEMBRO INFERIOR',
  '883590': 'RESONANCIA MAGNETICA DE SISTEMA MUSCULO ESQUELETICO',
  '883901': 'RESONANCIA MAGNETICA DE CUERPO ENTERO',
  '883908': 'RESONANCIA MAGNETICA DE VASOS',
  '883909': 'RESONANCIA MAGNETICA CON ANGIOGRAFIA',

  // --- CODIGOS SOAT (5 DÍGITOS) ---
  '18707': 'CISTOSCOPIA Y PIELOGRAFIA RETROGADA',
  '21101': 'MANO - DEDOS - PUÑO - CODO - PIE - CLAVICULA - ANTEBRAZO',
  '21102': 'BRAZO - PIERNA - RODILLA - FEMUR - HOMBRO - OMOPLATO',
  '21103': 'TEST DE FARILL (OSTEOMETRIA) - PIE PLANO',
  '21104': 'TEST DE ANTEVERSION FEMORAL',
  '21105': 'PELVIS - CADERA - ARTICULACIONES SACRO ILIACAS',
  '21108': 'PROYECCION ADICIONAL (STRESS - TUNEL - TANGENCIALES)',
  '21109': 'TANGENCIAL ROTULA',
  '21111': 'ESTUDIO DE HUESOS LARGOS AP',
  '21113': 'OSTEODENSITOMETRIA POR ABSORCION DUAL DE RX',
  '21120': 'CARA - MALAR - ARCO CIGOMATICO - HUESOS NASALES',
  '21121': 'SENOS PARANASALES - MAXILAR INFERIOR - ORBITAS',
  '21122': 'CRANEO SIMPLE',
  '21123': 'CRANEO SIMPLE Y BASE DE CRANEO',
  '21124': 'MASTOIDES COMPARATIVAS - PENASCOS - CAI',
  '21136': 'CAVUM FARINGEO - CUELLO Y TEJIDOS BLANDOS',
  '21140': 'COLUMNA CERVICAL',
  '21141': 'COLUMNA DORSAL O TORAXICA',
  '21142': 'COLUMNA LUMBOSACRA',
  '21143': 'SACROCOCCIX',
  '21144': 'TEST DE ESCOLIOSIS',
  '21201': 'TORAX (PA O P A Y LATERAL) - REJA COSTAL',
  '21203': 'ESTERNON - ARTICULACIONES ESTERNO CLAVICULARES',
  '21210': 'MAMOGRAFIA (BILATERAL)',
  '21211': 'GALACTOGRAFIA',
  '21212': 'MAMOGRAFIA UNILATERAL',
  '21301': 'ABDOMEN SIMPLE',
  '21302': 'ABDOMEN SIMPLE SERIE DE ABDOMEN AGUDO',
  '21303': 'PIELOGRAFIA RETROGRADA',
  '21304': 'UROGRAFIA INTRAVENOSA',
  '21325': 'COLANGIOGRAFIA TOMOGRAFIA',
  '31306': 'ANGIORESONANCIA MAGNETICA',
  '886012': 'Osteodensitometría por Absorción Dual',
  '886013': 'Osteodensitometría y Composición Corporal',
};

const GENERATED_CUPS_DESCRIPTIONS: Record<string, string> = Object.fromEntries(
  Object.entries(GENERATED_CUPS_METADATA).map(([code, metadata]) => [code, (metadata as any).description])
);

export const CUPS_CODES: Record<string, string> = {
  ...LEGACY_CODES,
  ...GENERATED_CUPS_DESCRIPTIONS,
};

/**
 * Derives the medical modality (RX, TAC, ECO, etc.) from a CUPS or SOAT code.
 */
export function getModalityFromCUPS(code: string): string | null {
  const meta = GENERATED_CUPS_METADATA[code as any];
  if (meta) {
    return MODALITY_MAPPING[meta.modality as CupsModality] || null;
  }

  // Fallback for SOAT and other legacy codes
  if (code.startsWith('217')) return 'TAC';
  if (code.startsWith('211') || code.startsWith('212') || code.startsWith('87') && !code.startsWith('879')) return 'RX';
  if (code.startsWith('213')) return 'RX'; // Digestive radiographies
  if (code.startsWith('311') || code.startsWith('187')) return 'ECO';
  if (code.startsWith('313')) return 'RMN';
  if (code.startsWith('879')) return 'TAC';
  if (code.startsWith('881') || code.startsWith('882')) return 'ECO';
  if (code.startsWith('883')) return 'RMN';

  return null;
}

type SupportedModality = 'RX' | 'TAC' | 'ECO' | 'RMN' | 'MAMO';

const MODALITY_MAPPING: Record<CupsModality, SupportedModality> = {
  RX: 'RX',
  TAC: 'TAC',
  ECO: 'ECO',
  RMN: 'RMN',
  MG: 'MAMO',
  DENSITO: 'RX',
  HEMODINAMIA: 'RX',
};

type KeywordEntry = {
  code: string;
  keywords: string[];
};

const EXACT_MATCHES = new Map<string, string>();
const KEYWORD_INDEX: KeywordEntry[] = [];

function normalizeText(input: string): string {
  return input
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim();
}

/**
 * Maps a medical study description to its most likely CUPS or SOAT code.
 * Uses a combination of exact matching and keyword-based fuzzy search.
 */
export function mapStudyToCUPS(description: string, modality?: CupsModality): string | null {
  const normalized = normalizeText(description);

  // Initialize index on first run
  if (EXACT_MATCHES.size === 0) {
    Object.entries(CUPS_CODES).forEach(([code, desc]) => {
      const normDesc = normalizeText(desc);
      EXACT_MATCHES.set(normDesc, code);
      
      const keywords = normDesc.split(/\s+/).filter(w => w.length > 3);
      KEYWORD_INDEX.push({ code, keywords });
    });
  }

  // 1. Check exact matches
  if (EXACT_MATCHES.has(normalized)) {
    return EXACT_MATCHES.get(normalized)!;
  }

  // 2. Fuzzy match based on keywords
  const inputKeywords = normalized.split(/\s+/).filter(w => w.length > 2);
  let bestMatch: string | null = null;
  let maxScore = 0;

  for (const entry of KEYWORD_INDEX) {
    let score = 0;
    for (const kw of inputKeywords) {
      if (entry.keywords.includes(kw)) {
        score += 2;
      } else if (entry.keywords.some(ek => ek.startsWith(kw))) {
        score += 1;
      }
    }

    // Weight by modality if provided
    if (modality) {
      const mappedModality = MODALITY_MAPPING[modality];
      const codeStart = entry.code.substring(0, 2);
      
      // Basic CUPS/SOAT modality heuristics
      if (mappedModality === 'RX' && (entry.code.startsWith('87') || entry.code.startsWith('211') || entry.code.startsWith('212'))) score += 1;
      if (mappedModality === 'TAC' && (entry.code.startsWith('879') || entry.code.startsWith('217'))) score += 1;
      if (mappedModality === 'ECO' && (entry.code.startsWith('881') || entry.code.startsWith('882') || entry.code.startsWith('311'))) score += 1;
      if (mappedModality === 'RMN' && (entry.code.startsWith('883') || entry.code.startsWith('313'))) score += 1;
    }

    if (score > maxScore) {
      maxScore = score;
      bestMatch = entry.code;
    }
  }

  // Only return if confidence is high enough
  return maxScore >= 2 ? bestMatch : null;
}
